version: '3.1'

services:

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_HOST=database
    ports:
      - "3000:3000"
    restart: always
    links:
      - database
  database:
    image: timescale/timescaledb-ha:pg14-latest
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test-task-db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
